name: LobbyPopping
main: com.comze_instancelabs.lobbypopping.Main
version: 1.0
author: instancelabs
commands:
   anim:
      description: Try the particle effects on your own character
      usage: /anim [name]